### ISSUE TITLE
[BUG] Filter when using / selecting /creating trends is not working

### ISSUE THREAD

**Issue by shaarkys** [MadMonkey87/Homey.InsightTrends#2]
**Describe the bug**
Would it be please possible to fix filter when using / selecting /creating trends ?

**To Reproduce**
1. Go to New Flow
2. Click on  Insights Trend
3. Select Trend Calculated
4. Choose Select an Item
5. Click on Search -- enter anything - the list is not getting filtered

**Expected behavior**
Based on filtered words, list get filtered

**Screenshots**

![obrazek](https://user-images.githubusercontent.com/14859895/114085733-09be5000-98b2-11eb-8403-083fa5c8e72c.png)

**Additional context**
same happens for Calculate trend action, when selecting ITEM

Thank you.

**Comment by MadMonkey87** [comment]
This indeed is on Athoms side and will be fixed by them according to https://github.com/athombv/homey-apps-sdk-issues/issues/189#issuecomment-816557608

**Comment by MadMonkey87** [comment]
I am not sure if this is in the app or homey, see https://github.com/athombv/homey-apps-sdk-issues/issues/191

**Comment by shaarkys** [comment]
Thank you, I was first thinking the same hower it works in some apps...let me check

**Comment by shaarkys** [comment]
Timer App for example, Timer selection works just fine...not sure if it helps.

![Screenshot_20210409-192239_Homey.jpg](https://user-images.githubusercontent.com/14859895/114218107-48631180-9969-11eb-837d-cf357b0eba75.jpg)

![SmartSelect_20210409-192301_Homey.jpg](https://user-images.githubusercontent.com/14859895/114218114-4bf69880-9969-11eb-8eee-d0b8f93d811e.jpg)

**Comment by shaarkys** [comment]
https://github.com/lvanderree/com.synplyworks.thenmore/tree/master

**Comment by MadMonkey87** [comment]
It was indeed in the app and is now fixed, see https://homey.app/de-ch/app/ch.philippewechsler.trends/Insight-Trends/test/

**Comment by shaarkys** [comment]
Actually now it is reacting on filter but upon filter it's always empty.

**Comment by shaarkys** [comment]
In version 2.1.2...

**Comment by MadMonkey87** [comment]
What do you mean by that?

**Comment by shaarkys** [comment]
Apologies - it seems it's not working for cases like :
- When - Trend Calculated (Boolean) - Insight --> Select Item  ---> same as before
- And Condition --> Analyse Insights (boolean) --> Insight -> Select time ----> what ever you type, you got empty selection
- Then --> Calculate trend -->  Insight -->  what ever you type, you got empty selection

**Comment by MadMonkey87** [comment]
You're right, I've fixed it with 2.1.3;)

**Comment by shaarkys** [comment]
Working great, thank you for your fix and fantastic job, I really like what you have created, it has great potential.

**Comment by BOverdevest** [comment]
@MadMonkey87 For me issue is not resolved or it has returned. I'm on version 2.2.0

<img width="398" alt="Schermafbeelding 2021-05-12 om 20 42 49" src="https://user-images.githubusercontent.com/37892181/118031063-63f57980-b366-11eb-8bda-434e37f6912a.png">

**Comment by MadMonkey87** [comment]
Hey @BOverdevest 
This is an issue in the web app itself, Athom will fix it, see https://github.com/athombv/homey-apps-sdk-issues/issues/205
